# Generated by Django 2.2 on 2019-05-07 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20190505_1904'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='sunday',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
