# Generated by Django 2.2 on 2019-05-07 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_classroom_sunday'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='friday',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='classroom',
            name='monday',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='classroom',
            name='saturday',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='classroom',
            name='thursday',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='classroom',
            name='tuesday',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='classroom',
            name='wednesday',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
