# Generated by Django 2.2 on 2019-05-18 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='running',
            field=models.BooleanField(default=False),
        ),
    ]
