# Generated by Django 2.2 on 2019-05-27 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20190519_2054'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortalToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('token', models.CharField(max_length=50)),
            ],
        ),
    ]
