# Generated by Django 2.2 on 2019-05-28 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_portaltoken'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PortalToken',
        ),
        migrations.AddField(
            model_name='user',
            name='token',
            field=models.CharField(default='', max_length=50),
        ),
    ]
