# Generated by Django 2.2 on 2019-07-19 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='model_pic',
            field=models.ImageField(default='propics/propic.png', upload_to='propics/'),
        ),
    ]
