# Generated by Django 2.2 on 2019-07-19 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_user_model_pic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='model_pic',
            new_name='propic',
        ),
    ]
