# Generated by Django 2.2 on 2019-07-20 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20190719_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='propic',
            field=models.ImageField(default='media/propics/propic.png', upload_to='media/propics/'),
        ),
    ]
