# Generated by Django 2.2 on 2019-07-20 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_auto_20190720_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='propic',
            field=models.ImageField(default='media/propics/propic.png', upload_to='propics/'),
        ),
    ]
